spring.application.name=menufacil
server.port=${PORT}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Configuração global de CORS
spring.mvc.cors.path-pattern=/**
spring.mvc.cors.allowed-origins=https://menu-facil-dusky.vercel.app,http://localhost:4200
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
spring.mvc.cors.max-age=3600
