spring.application.name=menufacil
server.port=8100

# MongoDB
spring.data.mongodb.uri=mongodb+srv://mongodb:mongodb@cluster0.vnnw0ur.mongodb.net/menufacil?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

